export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS"
export const GET_COMMENTS_FAIL = "GET_COMMENTS_FAIL"
export const ADD_COMMENT_SUCCESS = "GET_COMMENTS_FAIL"
export const ADD_COMMENT_FAIL = "GET_COMMENTS_FAIL"
